services:
  # 1. DATABASE (MySQL)
  obs-mysql:
    image: mysql:8.0
    container_name: obs_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: obs_database
      MYSQL_PASSWORD: AnkaraScienceUniver2020
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. CACHE (Redis)
  obs-redis:
    image: redis:alpine
    container_name: obs_redis_cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data: