version: '3.8'

services:
  # ANA VERİTABANI
  obs-mysql:
    image: mysql:8.0
    container_name: obs_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: obs_database
      MYSQL_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # CACHE FOR REDIS
  obs-redis:
    image: redis:alpine
    container_name: obs_redis_cache
    restart: always
    ports:
      - "6379:6379"

  # RABBITMQ MESAJ KUYRUĞU
  obs-rabbitmq:
    image: rabbitmq:3-management
    container_name: obs_message_queue
    restart: always
    ports:
      - "5672:5672"   # Kodların bağlanacağı port
      - "15672:15672" # Tarayıcıdan gireceğimiz yönetim paneli portu

volumes:
  mysql_data: # Veritabanı verilerinin bilgisayarı kapattığında silinmemesi için