CREATE DATABASE IF NOT EXISTS obs_database;





USE obs_database;



















































CREATE TABLE FAKULTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Ad VARCHAR(255) NOT NULL
);


CREATE TABLE BOLUM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Fakulte_ID INT NOT NULL,
    Ad VARCHAR(255) NOT NULL,
    FOREIGN KEY (Fakulte_ID) REFERENCES FAKULTE(ID)
);


CREATE TABLE PROGRAM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Bolum_ID INT NOT NULL,
    Ad VARCHAR(255) NOT NULL,
    Tur VARCHAR(50) NOT NULL,
    FOREIGN KEY (Bolum_ID) REFERENCES BOLUM(ID)
);


CREATE TABLE DERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Kod VARCHAR(50) NOT NULL,
    Ad VARCHAR(255) NOT NULL,
    Kredi INT NOT NULL,
    AKTS INT NOT NULL,
    Teorik_Saat INT NOT NULL,
    Pratik_Saat INT NOT NULL
);


CREATE TABLE AKADEMIK_PERSONEL (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Unvan VARCHAR(100),
    Ad VARCHAR(100) NOT NULL,
    Soyad VARCHAR(100) NOT NULL,
    Bolum_ID INT NOT NULL,
    FOREIGN KEY (Bolum_ID) REFERENCES BOLUM(ID)
);


CREATE TABLE OGRENCI (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Ogrenci_No VARCHAR(50) UNIQUE NOT NULL,
    TCKN VARCHAR(11) UNIQUE NOT NULL,
    Ad VARCHAR(100) NOT NULL,
    Soyad VARCHAR(100) NOT NULL,
    Eposta VARCHAR(150) UNIQUE NOT NULL,
    Telefon VARCHAR(20),
    Adres TEXT,
    Durum VARCHAR(50),
    Program_ID INT NOT NULL,
    Danisman_ID INT,
    GPA DECIMAL(3,2),
    CGPA DECIMAL(3,2),
    FOREIGN KEY (Program_ID) REFERENCES PROGRAM(ID),
    FOREIGN KEY (Danisman_ID) REFERENCES AKADEMIK_PERSONEL(ID)
);


CREATE TABLE DERS_ONKOSUL (
    Ders_ID INT NOT NULL,
    Onkosul_Ders_ID INT NOT NULL,
    Gecme_Zorunlu_Mu BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (Ders_ID, Onkosul_Ders_ID),
    FOREIGN KEY (Ders_ID) REFERENCES DERS(ID),
    FOREIGN KEY (Onkosul_Ders_ID) REFERENCES DERS(ID)
);


CREATE TABLE MUFREDAT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Program_ID INT NOT NULL,
    Yil VARCHAR(10) NOT NULL,
    Versiyon VARCHAR(50),
    FOREIGN KEY (Program_ID) REFERENCES PROGRAM(ID)
);

CREATE TABLE MUFREDAT_DERSLERI (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Mufredat_ID INT NOT NULL,
    Ders_ID INT NOT NULL,
    Yariyil INT NOT NULL,
    Zorunlu_Mu BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (Mufredat_ID) REFERENCES MUFREDAT(ID),
    FOREIGN KEY (Ders_ID) REFERENCES DERS(ID)
);



































































CREATE TABLE AKADEMIK_TAKVIM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Yil VARCHAR(20),
    Donem VARCHAR(20),
    Baslangic DATE,
    Bitis DATE
);


CREATE TABLE ACILAN_DERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Ders_ID INT NOT NULL,
    Akademik_Takvim_ID INT NOT NULL,

    FOREIGN KEY (Ders_ID) REFERENCES DERS(ID),
    FOREIGN KEY (Akademik_Takvim_ID) REFERENCES AKADEMIK_TAKVIM(ID)
);


CREATE TABLE SUBE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Acilan_Ders_ID INT NOT NULL,
    Sube_Kodu VARCHAR(10),
    Akademik_Personel_ID INT NOT NULL,
    Kontenjan INT,

    FOREIGN KEY (Acilan_Ders_ID) REFERENCES ACILAN_DERS(ID),
    FOREIGN KEY (Akademik_Personel_ID) REFERENCES AKADEMIK_PERSONEL(ID)
);


CREATE TABLE DERS_KAYIT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Ogrenci_ID INT NOT NULL,
    Sube_ID INT NOT NULL,
    Danisman_Onayi BOOLEAN,
    Durum VARCHAR(50),

    FOREIGN KEY (Ogrenci_ID) REFERENCES OGRENCI(ID),
    FOREIGN KEY (Sube_ID) REFERENCES SUBE(ID)
);



CREATE TABLE NOTLANDIRMA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Ders_Kayit_ID INT NOT NULL,
    Sinav_Turu VARCHAR(20),
    Puan DECIMAL(5,2),
    Itiraz_Var_Mi BOOLEAN,

    FOREIGN KEY (Ders_Kayit_ID) REFERENCES DERS_KAYIT(ID)
);


CREATE TABLE DONEM_NOTU (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Ders_Kayit_ID INT NOT NULL,
    Harf_Notu VARCHAR(5),
    Kilitli_Mi BOOLEAN,
    Gecti_Mi BOOLEAN,

    FOREIGN KEY (Ders_Kayit_ID) REFERENCES DERS_KAYIT(ID)
);



CREATE TABLE DEVAMSIZLIK (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Ders_Kayit_ID INT NOT NULL,
    Tarih DATE,
    Saat TIME,
    Durum VARCHAR(20),

    FOREIGN KEY (Ders_Kayit_ID) REFERENCES DERS_KAYIT(ID)
);



CREATE TABLE DERSLIK (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Ad VARCHAR(100),
    Kapasite INT,
    Tip VARCHAR(50)
);



CREATE TABLE DERS_PROGRAMI (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Sube_ID INT NOT NULL,
    Derslik_ID INT NOT NULL,
    Gun VARCHAR(20),
    Baslangic_Saat TIME,

    FOREIGN KEY (Sube_ID) REFERENCES SUBE(ID),
    FOREIGN KEY (Derslik_ID) REFERENCES DERSLIK(ID)
);



CREATE TABLE SINAV_PROGRAMI (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Sube_ID INT NOT NULL,
    Sinav_Turu VARCHAR(50),
    Tarih DATE,
    Saat TIME,

    FOREIGN KEY (Sube_ID) REFERENCES SUBE(ID)
);



CREATE TABLE SINAV_SALON_GOZETMEN (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Sinav_Programi_ID INT NOT NULL,
    Derslik_ID INT NOT NULL,
    Gozetmen_ID INT NOT NULL,

    FOREIGN KEY (Sinav_Programi_ID) REFERENCES SINAV_PROGRAMI(ID),
    FOREIGN KEY (Derslik_ID) REFERENCES DERSLIK(ID),
    FOREIGN KEY (Gozetmen_ID) REFERENCES AKADEMIK_PERSONEL(ID)
);



CREATE TABLE DANISMANLIK_GORUSMESI (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Danisman_ID INT NOT NULL,
    Ogrenci_ID INT NOT NULL,
    Tarih DATE,
    Konu VARCHAR(255),

    FOREIGN KEY (Danisman_ID) REFERENCES AKADEMIK_PERSONEL(ID),
    FOREIGN KEY (Ogrenci_ID) REFERENCES OGRENCI(ID)
);



CREATE TABLE CAP_YANDAL (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Ogrenci_ID INT NOT NULL,
    Program_ID INT NOT NULL,
    Tur VARCHAR(50),
    Durum VARCHAR(50),

    FOREIGN KEY (Ogrenci_ID) REFERENCES OGRENCI(ID),
    FOREIGN KEY (Program_ID) REFERENCES PROGRAM(ID)
);



CREATE TABLE DERS_ESDEGERLIK (
    Ders_ID INT NOT NULL,
    Esdeger_Ders_ID INT NOT NULL,

    PRIMARY KEY (Ders_ID, Esdeger_Ders_ID),

    FOREIGN KEY (Ders_ID) REFERENCES DERS(ID),
    FOREIGN KEY (Esdeger_Ders_ID) REFERENCES DERS(ID)
);



CREATE TABLE KULLANICI (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Eposta VARCHAR(150) UNIQUE NOT NULL,
    Sifre_Hash VARCHAR(255) NOT NULL,
    Rol VARCHAR(50) NOT NULL,
    Basarisiz_Giris_Sayisi INT DEFAULT 0,
    Hesap_Kilitli_Mi BOOLEAN DEFAULT FALSE,
    Kilit_Zamani DATETIME,
    Son_Aktivite DATETIME,
    Olusturulma_Tarihi DATETIME DEFAULT CURRENT_TIMESTAMP
);
